export const estados = [
  { sigla: "AC", nome: "Acre" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "RR", nome: "Roraima" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "TO", nome: "Tocantins" },
];

export const cidades: Record<string, string[]> = {
  AC: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá", "Feijó", "Brasiléia", "Plácido de Castro", "Xapuri", "Epitaciolândia", "Rodrigues Alves", "Mâncio Lima"],
  AL: ["Maceió", "Arapiraca", "Rio Largo", "Penedo", "Palmeira dos Índios", "Delmiro Gouveia", "Coruripe", "Marechal Deodoro", "União dos Palmares", "São Miguel dos Campos", "Santana do Ipanema", "Murici", "Atalaia", "Campo Alegre", "Viçosa"],
  AM: ["Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Coari", "Tabatinga", "Maués", "Tefé", "Humaitá", "Lábrea", "Iranduba", "Careiro da Várzea", "Autazes", "Novo Aripuanã", "Presidente Figueiredo", "Rio Preto da Eva"],
  AP: ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque", "Porto Grande", "Mazagão", "Pedra Branca do Amapari", "Vitória do Jari"],
  BA: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna", "Ilhéus", "Lauro de Freitas", "Juazeiro", "Porto Seguro", "Barreiras", "Alagoinhas", "Simões Filho", "Valença", "Paulo Afonso", "Eunápolis", "Teixeira de Freitas", "Santo Antônio de Jesus", "Jequié", "Senhor do Bonfim", "Jacobina", "Guanambi", "Brumado", "Cruz das Almas", "Serrinha", "Caetité", "Itapetinga", "Irecê", "Lençóis", "Poções", "Amargosa"],
  CE: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral", "Crato", "Iguatu", "Quixadá", "Itapipoca", "Maranguape", "Aquiraz", "Pacatuba", "Horizonte", "Canindé", "Quixeramobim", "Tianguá", "Camocim", "Aracati", "Limoeiro do Norte", "Russas"],
  DF: ["Brasília", "Taguatinga", "Ceilândia", "Plano Piloto", "Samambaia", "Águas Claras", "Guará", "Sobradinho", "Planaltina", "Recanto das Emas", "Riacho Fundo", "Gama", "Núcleo Bandeirante", "Brazlândia"],
  ES: ["Vitória", "Vila Velha", "Serra", "Cariacica", "Linhares", "São Mateus", "Colatina", "Cachoeiro de Itapemirim", "Guarapari", "Aracruz", "Viana", "Anchieta", "Domingos Martins", "Santa Maria de Jetibá", "Piúma"],
  GO: ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia", "Catalão", "Trindade", "Formosa", "Valparaíso de Goiás", "Novo Gama", "Águas Lindas de Goiás", "Senador Canedo", "Goianésia", "Inhumas", "Itumbiara", "Jataí", "Caldas Novas", "Quirinópolis", "Ceres", "Morrinhos"],
  MA: ["São Luís", "Imperatriz", "São José de Ribamar", "Timon", "Caxias", "Codó", "Açailândia", "Paço do Lumiar", "Bacabal", "Balsas", "Santa Inês", "Barra do Corda", "Pinheiro", "Pedreiras", "Viana", "Chapadinha", "Colinas", "São João dos Patos", "Coroatá", "Zé Doca"],
  MG: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Uberaba", "Governador Valadares", "Ipatinga", "Sete Lagoas", "Divinópolis", "Ribeirão das Neves", "Santa Luzia", "Poços de Caldas", "Patos de Minas", "Pouso Alegre", "Teófilo Otoni", "Barbacena", "Varginha", "Conselheiro Lafaiete", "Lavras", "Itabira", "João Monlevade", "Muriaé", "Viçosa", "Caratinga", "Araguari", "Ituiutaba", "Coronel Fabriciano", "Sabará", "Vespasiano", "Pedro Leopoldo", "Lagoa Santa", "Itaúna", "Nova Lima"],
  MS: ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã", "Naviraí", "Nova Andradina", "Aquidauana", "Sidrolândia", "Maracaju", "Coxim", "Paranaíba", "Chapadão do Sul", "Anastácio", "Rio Brilhante"],
  MT: ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra", "Cáceres", "Sorriso", "Primavera do Leste", "Alta Floresta", "Barra do Garças", "Lucas do Rio Verde", "Nova Mutum", "Guarantã do Norte", "Juína", "Colíder"],
  PA: ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal", "Parauapebas", "Abaetetuba", "Cametá", "Bragança", "Altamira", "Tucuruí", "Barcarena", "Paragominas", "Redenção", "Tomé-Açu", "Capanema", "São Félix do Xingu", "Itaituba", "Marituba", "Benevides"],
  PB: ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux", "Sousa", "Cajazeiras", "Guarabira", "Cabedelo", "Sapé", "Mamanguape", "Esperança", "Monteiro", "Pombal", "Itabaiana"],
  PE: ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Paulista", "Cabo de Santo Agostinho", "Garanhuns", "Vitória de Santo Antão", "Camaragibe", "Igarassu", "Abreu e Lima", "Ipojuca", "Araripina", "Santa Cruz do Capibaribe", "Surubim", "Palmares", "Goiana", "Bezerros", "Belo Jardim", "Arcoverde", "São Lourenço da Mata", "Serra Talhada", "Pesqueira"],
  PI: ["Teresina", "Parnaíba", "Picos", "Floriano", "Campo Maior", "Barras", "Altos", "Pedro II", "União", "Piripiri", "São Raimundo Nonato", "Esperantina", "Oeiras", "Bom Jesus", "Corrente"],
  PR: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "São José dos Pinhais", "Foz do Iguaçu", "Colombo", "Guarapuava", "Paranaguá", "Araucária", "Toledo", "Apucarana", "Pinhais", "Campo Largo", "Almirante Tamandaré", "Umuarama", "Cambé", "Sarandi", "Francisco Beltrão", "Cianorte", "Paranavaí", "Pato Branco", "Campo Mourão", "Rolândia"],
  RJ: ["Rio de Janeiro", "Niterói", "Duque de Caxias", "Nova Iguaçu", "Campos dos Goytacazes", "Petrópolis", "Volta Redonda", "Macaé", "Belford Roxo", "São Gonçalo", "Mesquita", "Nilópolis", "São João de Meriti", "Magé", "Itaboraí", "Maricá", "Cabo Frio", "Angra dos Reis", "Resende", "Barra Mansa", "Teresópolis", "Queimados", "Japeri", "Nova Friburgo", "Três Rios"],
  RN: ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Ceará-Mirim", "Caicó", "Assu", "Macau", "Currais Novos", "Nova Cruz", "São José de Mipibu", "Extremoz", "Apodi", "João Câmara", "Areia Branca"],
  RO: ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal", "Rolim de Moura", "Guajará-Mirim", "Jaru", "Ouro Preto do Oeste", "Espigão D'Oeste", "Pimenta Bueno", "Machadinho D'Oeste"],
  RR: ["Boa Vista", "Rorainópolis", "Caracaraí", "Mucajaí", "Alto Alegre", "Pacaraima", "Normandia", "Cantá"],
  RS: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Novo Hamburgo", "Passo Fundo", "São Leopoldo", "Gravataí", "Viamão", "Alvorada", "Sapucaia do Sul", "Rio Grande", "Cachoeirinha", "Bagé", "Bento Gonçalves", "Erechim", "Lajeado", "Santa Cruz do Sul", "Uruguaiana", "Ijuí", "Sapiranga", "Montenegro", "Guaíba", "Cachoeira do Sul"],
  SC: ["Florianópolis", "Joinville", "Blumenau", "São José", "Chapecó", "Itajaí", "Criciúma", "Lages", "Palhoça", "Balneário Camboriú", "Brusque", "Tubarão", "São Bento do Sul", "Caçador", "Jaraguá do Sul", "Concórdia", "Araranguá", "Mafra", "Rio do Sul", "Camboriú"],
  SE: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "São Cristóvão", "Estância", "Tobias Barreto", "Simão Dias", "Propriá", "Itabaianinha", "Nossa Senhora das Dores", "Poço Redondo"],
  SP: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "Sorocaba", "Ribeirão Preto", "Mauá", "São Caetano do Sul", "Mogi das Cruzes", "Piracicaba", "Bauru", "Santos", "Jundiaí", "Limeira", "Franca", "Taubaté", "Carapicuíba", "São José dos Campos", "Diadema", "Suzano", "Taboão da Serra", "Embu das Artes", "Cotia", "Itaquaquecetuba", "Barueri", "Americana", "São Carlos", "Araraquara", "Presidente Prudente", "Marília", "Rio Claro", "Araçatuba", "São José do Rio Preto", "Jacareí", "Indaiatuba", "Hortolândia", "Praia Grande", "São Vicente", "Itapevi", "Francisco Morato", "Franco da Rocha", "Itapecerica da Serra", "Votorantim", "Botucatu", "Itu", "Sumaré", "Ferraz de Vasconcelos", "Guarujá"],
  TO: ["Palmas", "Araguaína", "Gurupi", "Porto Nacional", "Paraíso do Tocantins", "Colinas do Tocantins", "Guaraí", "Tocantinópolis", "Dianópolis", "Formoso do Araguaia", "Miracema do Tocantins", "Pedro Afonso"],
};

// Bairros por cidade — modelo híbrido: sugestões estruturadas + digitação livre
export const bairros: Record<string, string[]> = {

  // ── ACRE ──────────────────────────────────────────────────────────────────
  "Rio Branco": ["Centro", "Bosque", "Floresta", "Cadeia Velha", "Cidade Nova", "Habitasa", "Preventório", "Seis de Agosto", "Tancredo Neves", "Conquista", "Placas", "Sobral", "Calafate", "Bahia Velha", "Corrente"],
  "Cruzeiro do Sul": ["Centro", "Miritizal", "João Pessoa", "São Cristóvão", "Remanso", "Aeroporto", "Bairro Novo", "Cohab"],
  "Sena Madureira": ["Centro", "Bairro Novo", "Cohab", "Aeroporto", "Flor do Serrado"],
  "Tarauacá": ["Centro", "Bairro Novo", "Cohab", "Floresta", "Senador Guiomard"],
  "Feijó": ["Centro", "Bairro Novo", "Conjunto Habitacional", "Vila Rica"],
  "Brasiléia": ["Centro", "Bairro Novo", "Glória", "Cohab"],

  // ── ALAGOAS ───────────────────────────────────────────────────────────────
  "Maceió": ["Centro", "Ponta Verde", "Pajuçara", "Jatiúca", "Mangabeiras", "Farol", "Trapiche da Barra", "Poço", "Jaraguá", "Cruz das Almas", "Benedito Bentes", "Tabuleiro do Martins", "Fernão Velho", "Clima Bom", "Feitosa", "Jacintinho", "Levada", "Mutange", "Pinheiro", "Petrópolis", "Santos Dumont", "Serraria"],
  "Arapiraca": ["Centro", "Primavera", "Novo Horizonte", "Caçula", "Itaperinha", "Bom Jesus", "Santa Edwiges", "Planalto", "Cohab", "Jardim Esperança"],
  "Rio Largo": ["Centro", "Santa Amélia", "Bom Jesus", "Cohab"],
  "Penedo": ["Centro", "Cohab", "Alagoas", "Bairro Novo"],
  "Palmeira dos Índios": ["Centro", "Cohab", "Centenário", "Bairro Novo"],
  "União dos Palmares": ["Centro", "Bairro Novo", "São Benedito"],

  // ── AMAZONAS ──────────────────────────────────────────────────────────────
  "Manaus": ["Centro", "Adrianópolis", "Aleixo", "Alvorada", "Chapada", "Coroado", "Flores", "Japiim", "Lago Azul", "Nossa Senhora das Graças", "Parque 10 de Novembro", "Petrópolis", "São Geraldo", "São Jorge", "Tarumã", "Vieiralves", "Compensa", "Dom Pedro", "Jorge Teixeira", "Nova Esperança", "São Raimundo", "Aparecida", "Cachoeirinha", "Crespo", "Educandos", "Planalto", "Santo Agostinho", "Cidade Nova", "Novo Aleixo", "Armando Mendes", "Distrito Industrial I", "Raiz", "Glória", "Lírio do Vale"],
  "Parintins": ["Centro", "Palmares", "São Sebastião", "Djard Vieira", "Itaúna", "Francesa"],
  "Itacoatiara": ["Centro", "São Francisco", "Mutirão", "Bairro Novo"],
  "Manacapuru": ["Centro", "Codajás", "Bela Vista", "Bairro Novo"],
  "Iranduba": ["Centro", "Bela Vista", "Cacau Pirêra"],

  // ── AMAPÁ ─────────────────────────────────────────────────────────────────
  "Macapá": ["Centro", "Buritizal", "Congós", "Infraero", "Jardim Marco Zero", "Lagoa Azul", "Laguinho", "Novo Horizonte", "Santa Rita", "Santo Antônio", "Trem", "Zerão", "Beirol", "Boné Azul", "Cabralzinho", "Cidade Nova", "Marabaixo", "Perpétuo Socorro"],
  "Santana": ["Centro", "Igarapé das Mulheres", "Paraíso", "Amapá Velho", "Elesbão"],
  "Laranjal do Jari": ["Centro", "Monte Dourado", "Munguba"],
  "Oiapoque": ["Centro", "Paraíso", "Clevelândia do Norte"],

  // ── BAHIA ─────────────────────────────────────────────────────────────────
  "Salvador": ["Centro", "Barra", "Ondina", "Rio Vermelho", "Pituba", "Itaigara", "Caminho das Árvores", "Brotas", "Liberdade", "Cajazeiras", "Boca do Rio", "Patamares", "Stella Maris", "Itapuã", "Pernambués", "Sussuarana", "Cosme de Farias", "Pau da Lima", "São Caetano", "Federação", "Graça", "Vitória", "Santo Antônio", "Comércio", "Campo Grande", "Nazaré", "Barris", "García", "Politeama", "Dois de Julho", "Cabula", "Doron", "Tancredo Neves", "Valéria", "Periperi", "Plataforma", "Praia Grande", "Paripe", "Lobato", "Subúrbio Ferroviário", "Imbuí", "Stiep"],
  "Feira de Santana": ["Centro", "Kalilândia", "Tomba", "SIM", "Capuchinhos", "Brasília", "Queimadinha", "Caseb", "Campo Limpo", "Limoeiro", "Papagaio", "Cidade Nova", "Lagoa Grande", "Mangabeira"],
  "Vitória da Conquista": ["Centro", "Recreio", "Brasil", "Boa Vista", "Candeias", "Zabelê", "Jurema", "Patagônia", "Ibirapuera", "Urbis IV", "Espírito Santo"],
  "Camaçari": ["Centro", "Abrantes", "Monte Gordo", "Barra do Jacuípe", "Glória", "Novo Mundo"],
  "Ilhéus": ["Centro", "Malhado", "Pontal", "São Domingos", "Banco da Vitória", "Castália", "Hernani Sá"],
  "Lauro de Freitas": ["Centro", "Buraquinho", "Vilas do Atlântico", "Ipitanga", "Portão", "Caji", "Itinga"],
  "Itabuna": ["Centro", "Zildolândia", "Alto Maron", "Conceição", "Ferradas", "Lomanto Júnior"],
  "Juazeiro": ["Centro", "Massapê", "Dom Avelar", "Abobreira", "Cajueiro", "Novo Horizonte"],
  "Porto Seguro": ["Centro", "Taperapuã", "Arraial d'Ajuda", "Trancoso", "Coroa Vermelha", "Baracho"],
  "Barreiras": ["Centro", "Boa Sorte", "Morada Nobre", "Renato Gonçalves", "Bandeirantes"],
  "Jequié": ["Centro", "Mandacaru", "João Pessoa", "Joaquim Romão"],
  "Paulo Afonso": ["Centro", "Trocado", "Bairro Universitário", "Cohab"],
  "Eunápolis": ["Centro", "Alecrim", "Alto dos Pinheiros"],
  "Teixeira de Freitas": ["Centro", "Jardim Eucalipto", "Buracão", "Nova Esperança"],
  "Alagoinhas": ["Centro", "Conceição", "Jardim Vitória", "Boa Vista"],
  "Simões Filho": ["Centro", "Bom Jesus dos Passos", "Jardim Aeroporto"],
  "Santo Antônio de Jesus": ["Centro", "São Judas Tadeu", "Cohab"],
  "Senhor do Bonfim": ["Centro", "Cohab", "São Sebastião"],
  "Jacobina": ["Centro", "Bela Vista", "Alto Alegre"],
  "Itapetinga": ["Centro", "Coité", "Bela Vista"],
  "Guanambi": ["Centro", "Ceraíma", "Mutans"],

  // ── CEARÁ ─────────────────────────────────────────────────────────────────
  "Fortaleza": ["Centro", "Aldeota", "Meireles", "Fátima", "Benfica", "Jóquei Clube", "Montese", "Parangaba", "Messejana", "Maraponga", "Granja Portugal", "Barra do Ceará", "Pirambú", "Mucuripe", "Varjota", "Cocó", "Água Fria", "Serrinha", "Damas", "Engenheiro Luciano Cavalcante", "Dionísio Torres", "Joaquim Távora", "Papicu", "São Gerardo", "Vila Velha", "Quintino Cunha", "Autran Nunes", "Bom Jardim", "Granja Lisboa", "Lagoa Redonda", "Conjunto Ceará", "Passaré", "Aeroporto", "José Bonifácio", "Praia de Iracema", "Praia do Futuro I", "Praia do Futuro II", "Edson Queiroz", "Amadeu Furtado", "Parreão"],
  "Caucaia": ["Centro", "Jurema", "Parquelândia", "Araturi", "Iparana", "Cumbuco", "Parque Tabapuá", "Prefeito José Walter"],
  "Juazeiro do Norte": ["Centro", "Triângulo", "Limoeiro", "Salesianos", "Franciscanos", "João Pessoa", "Lagoa Seca", "Timbaúba"],
  "Maracanaú": ["Centro", "Jereissati I", "Jereissati II", "Parque Genibaú", "Novo Oriente", "Conjunto Metropolitano"],
  "Sobral": ["Centro", "Sinhá Sabóia", "Derby", "Terrenos Novos", "Cohab", "Dom Expedito", "Junco"],
  "Crato": ["Centro", "Pimenta", "Mirandão", "Seminário", "Lameiro"],
  "Itapipoca": ["Centro", "Planalto", "Bom Jesus"],
  "Maranguape": ["Centro", "Penedo", "Aconchego"],

  // ── DISTRITO FEDERAL ──────────────────────────────────────────────────────
  "Brasília": ["Asa Norte", "Asa Sul", "Lago Norte", "Lago Sul", "Noroeste", "Sudoeste", "Cruzeiro", "Octogonal", "Setor de Embaixadas Norte", "Setor de Embaixadas Sul", "Setor Bancário Norte", "Setor Bancário Sul", "Setor Comercial Norte", "Setor Comercial Sul"],
  "Taguatinga": ["Centro", "Taguatinga Norte", "Taguatinga Sul", "Setor C", "Setor D", "Setor E", "Areal", "Guariroba", "Setor O"],
  "Ceilândia": ["Centro", "Norte", "Sul", "P Norte", "P Sul", "QNM", "QNN", "Expansão do Setor O", "Setor O", "Pôr do Sol", "Sol Nascente"],
  "Samambaia": ["Norte", "Sul", "Quadra 100", "Quadra 200", "Quadra 300", "Quadra 400"],
  "Gama": ["Centro", "Leste", "Norte", "Oeste", "Sul", "Rural"],
  "Planaltina": ["Centro", "Arapoanga", "Buritis", "Daia", "Jardim Roriz"],
  "Recanto das Emas": ["Quadra 100", "Quadra 200", "Quadra 300", "Quadra 400", "Quadra 500", "Quadra 600"],
  "Águas Claras": ["Norte", "Sul", "Veredas", "Arniqueiras"],
  "Guará": ["Guará I", "Guará II", "Estrutural", "SCIA"],
  "Sobradinho": ["Sobradinho I", "Sobradinho II", "Centro", "Fercal"],

  // ── ESPÍRITO SANTO ────────────────────────────────────────────────────────
  "Vitória": ["Centro", "Praia do Canto", "Jardim da Penha", "Mata da Praia", "Bento Ferreira", "Fradinhos", "Jucutuquara", "Maruípe", "Santa Lúcia", "Enseada do Suá", "Ilha do Frade", "Goiabeiras", "Joana D'Arc", "Jardim Camburi", "Pontal de Camburi", "Antônio Honório", "Forte São João"],
  "Vila Velha": ["Centro", "Praia da Costa", "Itaparica", "Coqueiral", "Glória", "Cobilândia", "São Torquato", "Araçás", "Barra do Jucu", "Terra Vermelha", "Paul", "Riviera da Barra"],
  "Serra": ["Centro", "Jacaraípe", "Nova Almeida", "Colina de Laranjeiras", "Bairro de Fátima", "Jardim Carapina", "Laranjeiras", "Civit I", "Civit II", "Barcelona"],
  "Cariacica": ["Centro", "Alto Lage", "Itanhenga", "Jardim América", "Flexal", "Campo Grande", "Bairro República", "Tucumã"],
  "Guarapari": ["Centro", "Praia do Morro", "Muquiçaba", "Perocão", "Setiba"],
  "Linhares": ["Centro", "Bebedouro", "Novo Horizonte", "Aviso", "Três Bancas"],
  "Cachoeiro de Itapemirim": ["Centro", "Monte Belo", "Amaral", "BNH", "Aquidaban", "Coronel Borges"],

  // ── GOIÁS ─────────────────────────────────────────────────────────────────
  "Goiânia": ["Centro", "Setor Bueno", "Setor Marista", "Jardim América", "Setor Oeste", "Jardim Goiás", "Setor Sul", "Setor Norte Ferroviário", "Campinas", "Chácaras Retiro", "Vila Nova", "Setor dos Funcionários", "Setor Universitário", "Setor Pedro Ludovico", "Setor Aeroporto", "Nova Suíça", "Parque Amazônia", "Jardim Atlântico", "Setor Negrão de Lima", "Parque Lozandes", "Jardim Nova Era", "Setor Itatiaia", "Setor dos Afonsos"],
  "Aparecida de Goiânia": ["Centro", "Andrade Reis", "Setor Garavelo", "Setor dos Funcionários", "Vila Brasília", "Setor Ataíde"],
  "Anápolis": ["Centro", "Jundiaí", "Maracanã", "Bom Jesus", "Setor Norte", "Setor Sul", "Setor Maracanãzinho", "Jundiaí Industrial"],
  "Rio Verde": ["Centro", "Alzira Mutran", "Bairro Bom Jesus", "Colégio", "Ipiranga"],
  "Luziânia": ["Centro", "Setor Tradicional", "Jardim Ingá", "Residencial São Luís"],
  "Valparaíso de Goiás": ["Centro", "Jardim Cavour", "Pôr do Sol"],
  "Águas Lindas de Goiás": ["Centro", "Mansões Variante", "Jardim São Bartolomeu"],
  "Senador Canedo": ["Centro", "Residencial das Colinas", "Jardim Europa"],
  "Caldas Novas": ["Centro", "Jardim Quente", "Turista I", "Turista II"],
  "Catalão": ["Centro", "Jundiaí", "Jardim Mônaco", "Bairro Santana"],
  "Trindade": ["Centro", "Olinda", "Setor Residencial"],
  "Formosa": ["Centro", "Setor Leste", "Vila União", "Setor Oeste"],
  "Novo Gama": ["Centro", "Jardim Ingá", "Vila Esperança"],
  "Itumbiara": ["Centro", "Bairro Industrial", "Jardim Europa"],
  "Jataí": ["Centro", "Jardim Paraíso", "Setor Oeste", "Vila Nova"],

  // ── MARANHÃO ──────────────────────────────────────────────────────────────
  "São Luís": ["Centro", "Cohab Anil", "Coroadinho", "Itaqui-Bacanga", "João Paulo", "Olho d'Água", "Ponta d'Areia", "Renascença", "São Francisco", "Turu", "Vinhais", "Bequimão", "Araçagy", "Filipinho", "Anjo da Guarda", "Anil", "Diamante", "Vila Embratel", "Calhau", "Ponta do Farol", "Jardim São Cristóvão", "Jardim Tropical"],
  "Imperatriz": ["Centro", "Bacuri", "Juçaral", "Parque Shalon", "Jardim Eldorado", "Vila Nova", "Novo Horizonte"],
  "São José de Ribamar": ["Centro", "Maiobão", "Paço do Lumiar", "Bairro Novo"],
  "Timon": ["Centro", "Parque Piauí", "Planalto", "Renascença"],
  "Caxias": ["Centro", "Olho d'Água", "Centro Norte", "Bairro dos Ipês"],
  "Bacabal": ["Centro", "São Benedito", "Novo Horizonte"],
  "Balsas": ["Centro", "Jardim São Luís", "Altamira"],
  "Santa Inês": ["Centro", "Parque das Flores", "Bairro Novo"],

  // ── MINAS GERAIS ──────────────────────────────────────────────────────────
  "Belo Horizonte": ["Centro", "Savassi", "Funcionários", "Lourdes", "Santo Agostinho", "Floresta", "Santa Efigênia", "Pampulha", "Buritis", "Belvedere", "Sion", "Mangabeiras", "Gutierrez", "Cidade Nova", "Lagoinha", "Padre Eustáquio", "Carlos Prates", "Colégio Batista", "Sagrada Família", "Coração de Jesus", "Barro Preto", "Santa Lúcia", "Santa Inês", "Serra", "Castelo", "Caiçara", "Venda Nova", "Concórdia", "São Paulo", "Aarão Reis", "Floramar", "Tupi", "Jardim Vitória", "Barreiro", "Betânia", "Havaí", "Cinquentenário", "Dom Cabral", "Jardim América", "Calafate", "Gameleira", "Nova Suíça", "Grajaú", "Palmares", "Renascença", "Horto", "Luxemburgo", "São Bento"],
  "Uberlândia": ["Centro", "Santa Mônica", "Tibery", "Umuarama", "Martins", "Jardim Karaíba", "Lídice", "Morumbi", "Aparecida", "Altamira", "Brasil", "Jardim Brasília", "Luizote de Freitas", "Marta Helena", "Planalto", "Tubalina"],
  "Contagem": ["Centro", "Industrial", "Eldorado", "Ressaca", "Sede", "Jardim Riacho das Pedras", "Cabral", "Nacional"],
  "Juiz de Fora": ["Centro", "São Mateus", "Cascatinha", "Benfica", "Graminha", "Santa Luzia", "Bairro Industrial", "Linhares", "Manoel Honório", "Grama", "Jóquei Clube"],
  "Betim": ["Centro", "PTB", "Industrias", "Teresópolis", "Jardim das Alterosas", "Citrolândia"],
  "Montes Claros": ["Centro", "Ibituruna", "Morada do Parque", "Major Prates", "Santos Dumont", "Vila Oliveira", "Maracanã"],
  "Uberaba": ["Centro", "Abadia", "Alfredo Freire", "Mercês", "Nossa Senhora da Abadia", "Fabrício", "Jardim das Américas"],
  "Governador Valadares": ["Centro", "Ilha dos Araújos", "Santa Helena", "Esplanada", "Chácara Paraíso", "Bairro de Lourdes"],
  "Ipatinga": ["Centro", "Bom Retiro", "Horto", "Chácaras", "Cidade Nobre", "Cariru"],
  "Sete Lagoas": ["Centro", "Eldorado", "Canaan", "Bela Vista", "Gameleira"],
  "Divinópolis": ["Centro", "Niterói", "Nova Cidade", "Sidil", "Manoa"],
  "Ribeirão das Neves": ["Centro", "Providência", "Bairro Universitário"],
  "Poços de Caldas": ["Centro", "Jardim Belo Horizonte", "Bortolan", "Santa Rosália"],
  "Varginha": ["Centro", "Bairro Gramado", "Jardim Andere", "Novo Horizonte"],
  "Viçosa": ["Centro", "Nova Viçosa", "Santa Clara"],
  "Santa Luzia": ["Centro", "Novo Horizonte", "Jardim Alterosas", "Cohab"],
  "Patos de Minas": ["Centro", "Alvorada", "Caiçara", "Guarani", "Maravilha", "Jardim das Oliveiras"],
  "Pouso Alegre": ["Centro", "Aeroporto", "Bela Vista", "Jardim das Acácias", "Recanto"],
  "Teófilo Otoni": ["Centro", "Jardim Teófilo", "Santa Luzia", "Bela Vista", "Cascalho"],
  "Barbacena": ["Centro", "São Sebastião", "Santos Dumont", "Jardim Estoril"],
  "Conselheiro Lafaiete": ["Centro", "Bela Vista", "Jardim das Palmeiras", "Industrial"],
  "Lavras": ["Centro", "Jardim São José", "Padre Kolbe", "Santa Filomena"],
  "Itabira": ["Centro", "Fábrica", "Santa Efigênia", "Bela Vista"],
  "João Monlevade": ["Centro", "Dom Bosco", "Bela Vista", "Horto"],
  "Muriaé": ["Centro", "Catanzaro", "Bela Vista", "Ernestina"],
  "Caratinga": ["Centro", "Esperança", "Sete de Setembro", "Nossa Senhora das Graças"],
  "Araguari": ["Centro", "Maracanã", "Bom Jesus", "Jardim Ipanema"],
  "Ituiutaba": ["Centro", "Progresso", "Canaã", "Tupã"],
  "Coronel Fabriciano": ["Centro", "Silvestre", "Caladão", "São Judas"],
  "Sabará": ["Centro", "Borges", "Jardim Esperança"],
  "Nova Lima": ["Centro", "Jardim Canadá", "Vila da Serra", "Alphaville"],
  "Itaúna": ["Centro", "Santo Antônio", "Bela Vista", "Piedade"],

  // ── MATO GROSSO DO SUL ────────────────────────────────────────────────────
  "Campo Grande": ["Centro", "Carandá Bosque", "Chácara Cachoeira", "Jardim dos Estados", "Monte Castelo", "Tiradentes", "Vila Bandeirantes", "Coophatrabalho", "Cidade Morena", "Leblon", "São Conrado", "Autonomista", "Ipiranga", "Nova Lima", "Amambaí", "Universitário"],
  "Dourados": ["Centro", "Jardim Caramuru", "Jardim Flórida", "Vila São Francisco", "Parque do Lago", "Alvorada"],
  "Três Lagoas": ["Centro", "Jardim Paraíso", "Cohab", "Santo Antônio"],
  "Corumbá": ["Centro", "Cervejaria", "Dom Bosco", "Popular Nova"],
  "Ponta Porã": ["Centro", "Vila Carvalho", "Alto Garças", "Jardim Europa"],
  "Maracaju": ["Centro", "Bairro Industrial", "Jardim São Paulo"],

  // ── MATO GROSSO ───────────────────────────────────────────────────────────
  "Cuiabá": ["Centro", "Araés", "Bandeirantes", "Bosque da Saúde", "Duque de Caxias", "Goiabeiras", "Jardim Universitário", "Morada da Serra", "Quilombo", "Santa Rosa", "São Benedito", "Terra Nova", "Coxipó", "Pascoal Ramos", "Despraiado", "Dom Aquino", "Paiaguás"],
  "Várzea Grande": ["Centro", "Bairro Médico", "Cristo Rei", "Ribeirão do Lipa", "Jardim das Flores", "Ipase"],
  "Rondonópolis": ["Centro", "Jardim Florianópolis", "Residencial Flamboyant", "Coophalis", "Cidade Alta"],
  "Sinop": ["Centro", "Setor Comercial", "Jardim das Américas", "Jardim Imperial", "Área Industrial"],
  "Lucas do Rio Verde": ["Centro", "Parque Industrial", "Água Boa"],
  "Alta Floresta": ["Centro", "Jardim Tropical", "Água Fria"],

  // ── PARÁ ──────────────────────────────────────────────────────────────────
  "Belém": ["Centro", "Batista Campos", "Umarizal", "Nazaré", "São Brás", "Marco", "Sacramenta", "Telégrafo", "Castanheira", "Bengui", "Pedreira", "Condor", "Reduto", "Cidade Velha", "Cremação", "Guamá", "Terra Firme", "Jurunas", "Marambaia", "Souza", "Barreiro", "Tapanã", "Val-de-Cans", "Pratinha"],
  "Ananindeua": ["Centro", "Coqueiro", "Guanabara", "Icuí-Guajará", "Distrito Industrial", "Maguari"],
  "Santarém": ["Centro", "Aldeia", "Aeroporto Velho", "Tirolesa", "Maracanã", "Urumanduba"],
  "Marabá": ["Centro", "Cidade Nova", "Nova Marabá", "São Félix", "Morada Nova", "Amapá"],
  "Castanhal": ["Centro", "Jaderlândia", "Saudade", "Novo Horizonte"],
  "Parauapebas": ["Centro", "Rio Verde", "Palmares", "Carajás"],
  "Barcarena": ["Centro", "Vila dos Cabanos", "Bairro Novo"],
  "Bragança": ["Centro", "Aldeia", "Perpétuo Socorro"],

  // ── PARAÍBA ───────────────────────────────────────────────────────────────
  "João Pessoa": ["Centro", "Tambaú", "Manaíra", "Altiplano", "Bancários", "Castelo Branco", "Expedicionários", "Valentina", "Cristo Redentor", "Mandacaru", "Jaguaribe", "Roger", "Água Fria", "Ernesto Geisel", "Jardim Veneza", "Portal do Sol", "Bessa", "Cabo Branco", "Jardim Oceania", "Jardim São Paulo"],
  "Campina Grande": ["Centro", "Prata", "Bodocongó", "Dinamérica", "Mirante", "Jeremias", "Catolé", "Liberdade", "Universitário", "Estação Velha"],
  "Santa Rita": ["Centro", "Gramame", "Tibiri", "Jardim Manguape"],
  "Patos": ["Centro", "Jatobá", "Belo Horizonte", "Belo Horizonte II"],
  "Bayeux": ["Centro", "Miramar", "Esplanada", "Jardim Aeroporto"],
  "Cabedelo": ["Centro", "Ponta de Mato", "Renascer"],
  "Guarabira": ["Centro", "Novo Horizonte", "Jardim Santa Emília"],

  // ── PERNAMBUCO ────────────────────────────────────────────────────────────
  "Recife": ["Centro", "Boa Viagem", "Casa Forte", "Espinheiro", "Graças", "Madalena", "Boa Vista", "Aflitos", "Encruzilhada", "Várzea", "Pina", "Imbiribeira", "Água Fria", "Jardim São Paulo", "Torreão", "Torre", "Afogados", "Arruda", "Barbalho", "Boa Vista", "Bongi", "Brasilit", "Cabanga", "Cajueiro", "Campo Grande", "Campina do Barreto", "Caxangá", "Cidade Universitária", "Coelhos", "Cordeiro", "Curado", "Derby", "Dois Irmãos", "Guabiraba", "Hipódromo", "Ibura", "Iputinga", "Jaqueira", "Jordão", "Linha do Tiro", "Macaxeira", "Mangabeira", "Monteiro", "Mustardinha", "Prado", "Rosarinho", "San Martin", "Santana", "Santo Amaro", "Soledade", "Tejipió", "Vasco da Gama", "Zumbi"],
  "Jaboatão dos Guararapes": ["Centro", "Cavaleiro", "Prazeres", "Candeias", "Guararapes", "Barra de Jangada"],
  "Olinda": ["Centro", "Carmo", "Bairro Novo", "Rio Doce", "Jardim Brasil", "Jardim Atlântico", "Salgadinho"],
  "Caruaru": ["Centro", "Vassoural", "Maurício de Nassau", "Salgado", "São Francisco", "Bairro das Nações"],
  "Petrolina": ["Centro", "Cohab", "Caladinho", "Jardim Petrolina", "Cohab Massangano"],
  "Paulista": ["Centro", "Arthur Lundgren I", "Arthur Lundgren II", "Maria Farinha", "Maranguape I"],
  "Cabo de Santo Agostinho": ["Centro", "Pontezinha", "Novo Cabo", "Suape"],
  "Vitória de Santo Antão": ["Centro", "Bairro Novo", "Tiradentes"],
  "Camaragibe": ["Centro", "Aldeia", "Timbi"],
  "Igarassu": ["Centro", "Igarassu", "Nova Cruz"],
  "Santa Cruz do Capibaribe": ["Centro", "Bairro dos Novais", "Cohab"],
  "Serra Talhada": ["Centro", "Bairro Novo", "Cohab"],
  "Garanhuns": ["Centro", "Heliópolis", "São José", "Santo Antônio", "Magano", "Cohab", "Loteamento Alto do Caxangá", "Alto da Sela"],
  "Arcoverde": ["Centro", "Cohab", "Bairro Novo", "Caixa D'Água", "Indianópolis"],
  "Abreu e Lima": ["Centro", "Jardim Brasil", "Monte Verde", "Pacheco"],
  "Goiana": ["Centro", "Goiana", "Tejucopapo"],
  "Bezerros": ["Centro", "Bom Jesus", "Cohab"],
  "Belo Jardim": ["Centro", "Cohab", "Novo Horizonte"],
  "São Lourenço da Mata": ["Centro", "Jardim Monte Verde", "Cohab"],
  "Pesqueira": ["Centro", "Cohab", "Bela Vista"],
  "Surubim": ["Centro", "Cohab", "Bairro Novo"],
  "Palmares": ["Centro", "Cohab", "São Sebastião"],
  "Araripina": ["Centro", "Cohab", "Jardim Novo"],
  "Ipojuca": ["Centro", "Ipojuca", "Nossa Senhora do Ó"],

  // ── PIAUÍ ─────────────────────────────────────────────────────────────────
  "Teresina": ["Centro", "Fátima", "Ilhotas", "Jóquei", "Leste", "Matinha", "Mocambinho", "Noivos", "Piçarra", "São Cristóvão", "Dirceu Arcoverde", "São João", "Recanto dos Vinhais", "Monte Castelo", "Memorare", "Cristo Rei", "São Raimundo", "Renascença", "Buenos Aires"],
  "Parnaíba": ["Centro", "Aeroporto", "Cohab", "Ilha Grande", "Bairro dos Nobres"],
  "Picos": ["Centro", "Junco", "Universitário", "Canto da Várzea"],
  "Floriano": ["Centro", "Cohab", "Coronel Olimpio"],
  "Campo Maior": ["Centro", "Cohab", "Antônio Batista"],
  "Piripiri": ["Centro", "Cohab", "Setor Norte"],

  // ── PARANÁ ────────────────────────────────────────────────────────────────
  "Curitiba": ["Centro", "Água Verde", "Batel", "Bigorrilho", "Boa Vista", "Cabral", "Cristo Rei", "Portão", "Juvevê", "Mercês", "Prado Velho", "Santa Felicidade", "Seminário", "Tingui", "Uberaba", "Cajuru", "Xaxim", "Sítio Cercado", "Fazendinha", "Novo Mundo", "Hauer", "Capão da Imbuia", "Boqueirão", "Alto Boqueirão", "Tatuquara", "Campo de Santana", "Pinheirinho", "Capão Raso", "Lindóia", "São Braz", "Pilarzinho", "Abranches", "Barreirinha", "Bacacheri", "Ahú", "Hugo Lange", "São Lourenço", "Orleans", "Augusta", "Campo Comprido", "Campina do Siqueira"],
  "Londrina": ["Centro", "Gleba Palhano", "Higienópolis", "Catuaí", "Jardim Shangrilá", "Jardim Esperança", "Cafezal", "Bandeirantes", "Vila Casoni"],
  "Maringá": ["Centro", "Zona 01", "Zona 02", "Zona 05", "Zona 07", "Zona 08", "Novo Horizonte", "Mandacaru", "Jardim Niterói", "Jardim Imperial"],
  "Ponta Grossa": ["Centro", "Contorno", "Jardim Carvalho", "Uvaranas", "Órfãs", "Nova Rússia"],
  "Cascavel": ["Centro", "Cascavel Velho", "Santa Cruz", "Neva", "Country", "Periolo"],
  "São José dos Pinhais": ["Centro", "Colônia Dona Luíza", "Afonso Pena", "Borda do Campo"],
  "Foz do Iguaçu": ["Centro", "Vila A", "Três Lagoas", "Morumbi", "Carimã", "Jardim América", "Jardim Europa"],
  "Colombo": ["Centro", "Jardim Bela Vista", "Roça Grande", "Monza"],
  "Guarapuava": ["Centro", "Boqueirão", "Morro Alto", "Jardim das Américas"],
  "Paranaguá": ["Centro", "Jardim Iguaçu", "Rocio", "Vila Portuária"],
  "Araucária": ["Centro", "Campina da Barra", "Costeira"],
  "Toledo": ["Centro", "Jardim Europa", "Industrial"],
  "Apucarana": ["Centro", "Jardim Mônaco", "Jardim Ponta Grossa"],
  "Pinhais": ["Centro", "Jardim Tarumã", "Maria Antonieta"],
  "Campo Largo": ["Centro", "Jardim Maracanã", "Rondinha"],
  "Umuarama": ["Centro", "Parque das Palmeiras", "Zona II"],
  "Cambé": ["Centro", "Jardim Hortência", "Alvorada"],
  "Sarandi": ["Centro", "Jardim Monte Rei"],
  "Pato Branco": ["Centro", "Fraron", "La Salle"],
  "Campo Mourão": ["Centro", "Jardim Tropical", "Jardim Paraíso"],

  // ── RIO DE JANEIRO ────────────────────────────────────────────────────────
  "Rio de Janeiro": ["Centro", "Barra da Tijuca", "Botafogo", "Copacabana", "Flamengo", "Ipanema", "Jardim Botânico", "Lagoa", "Leblon", "Maracanã", "Méier", "Penha", "Santa Teresa", "Tijuca", "Vila Isabel", "Bangu", "Campo Grande", "Jacarepaguá", "Recreio dos Bandeirantes", "Ilha do Governador", "Ramos", "Madureira", "Engenho Novo", "Irajá", "Vila da Penha", "Vigário Geral", "Realengo", "Anchieta", "Pavuna", "Oswaldo Cruz", "Cosmos", "Santa Cruz", "Pedra de Guaratiba", "Glória", "Catete", "Cosme Velho", "Laranjeiras", "Urca", "Humaitá", "Gávea", "São Cristóvão", "Praça da Bandeira", "Alto da Boa Vista", "Andaraí", "Grajaú", "Rio Comprido", "Estácio", "Lapa", "Bonsucesso", "Olaria", "Brás de Pina", "Inhaúma", "Higienópolis"],
  "Niterói": ["Centro", "Icaraí", "Fonseca", "Ingá", "São Francisco", "Itaipu", "Charitas", "Pendotiba", "Santa Rosa", "Jurujuba", "Piratininga"],
  "Duque de Caxias": ["Centro", "25 de Agosto", "Gramacho", "Jardim Gramacho", "Saracuruna", "Doutor Laureano", "Campos Elíseos"],
  "Nova Iguaçu": ["Centro", "Austin", "Cabuçu", "Califórnia", "Comendador Soares", "Moquetá", "Jardim Alvorada"],
  "São Gonçalo": ["Centro", "Arsenal", "Alcântara", "Zé Garoto", "Trindade", "Largo da Ideia"],
  "Belford Roxo": ["Centro", "Heliópolis", "São Bernardo", "Vila Pauline"],
  "São João de Meriti": ["Centro", "Vilar dos Teles", "Jardim Metrópolis"],
  "Campos dos Goytacazes": ["Centro", "Parque Aldeia", "Jockey Clube", "São José", "Goitacazes"],
  "Petrópolis": ["Centro", "Itaipava", "Quitandinha", "Cascatinha", "Correas"],
  "Volta Redonda": ["Centro", "Aterrado", "Niterói", "Roma", "Jardim Belmonte"],
  "Macaé": ["Centro", "Lagomar", "Nova Holanda", "Imboassica", "Mirante da Lagoa"],
  "Cabo Frio": ["Centro", "Jardim Excelsior", "Manoel Corrêa", "Braga"],
  "Teresópolis": ["Centro", "Alto", "Fonte Santa"],
  "Angra dos Reis": ["Centro", "Jacuecanga", "Frade", "Mambucaba"],

  // ── RIO GRANDE DO NORTE ───────────────────────────────────────────────────
  "Natal": ["Centro", "Alecrim", "Capim Macio", "Lagoa Nova", "Lagoa Seca", "Petrópolis", "Ponta Negra", "Ribeira", "Tirol", "Candelária", "Felipe Camarão", "Cidade da Esperança", "Cidade Nova", "Quintas", "Bom Pastor", "Nossa Senhora de Nazaré", "Mãe Luiza", "Rocas", "Santos Reis", "Potengi", "Nordeste", "Igapó", "Pajuçara", "Planalto"],
  "Mossoró": ["Centro", "Alto de São Manoel", "Bom Jardim", "Ilha de Santa Luzia", "Nova Betânia", "Lagoa do Mato", "Aeroporto", "Costa e Silva"],
  "Parnamirim": ["Centro", "Emaús", "Liberdade", "Nova Parnamirim", "Parque das Nações"],
  "São Gonçalo do Amarante": ["Centro", "Bom Pastor", "Redinha"],
  "Caicó": ["Centro", "Penedo", "Walfredo Gurgel", "Santos Reis"],
  "Currais Novos": ["Centro", "Alto da Boa Vista"],

  // ── RONDÔNIA ──────────────────────────────────────────────────────────────
  "Porto Velho": ["Centro", "Eldorado", "Flodoaldo Pontes Pinto", "Igarapé", "Nova Floresta", "Pedrinhas", "Tancredo Neves", "Aponiã", "Lagoa", "Nacional", "São Cristóvão", "Industrial"],
  "Ji-Paraná": ["Centro", "Jardim Botânico", "Urupá", "Nova Brasília", "Três Marias"],
  "Ariquemes": ["Centro", "Setor 01", "Setor 02", "Setor 03", "Setor 04", "Setor 06"],
  "Vilhena": ["Centro", "Bairro dos Estados", "Industrial", "Jardim Europa"],
  "Cacoal": ["Centro", "Jardim Clodoaldo", "Teixeirópolis", "Beira Rio"],
  "Rolim de Moura": ["Centro", "Setor 01", "Setor 02", "Setor Jardim das Flores"],

  // ── RORAIMA ───────────────────────────────────────────────────────────────
  "Boa Vista": ["Centro", "Caçari", "Jardim Caranã", "Liberdade", "Mecejana", "Pintolândia", "São Bento", "São Pedro", "Cauamé", "Buritis", "Nova Canaã", "Operário", "União"],
  "Rorainópolis": ["Centro", "Novo Paraíso", "Senador Hélio Campos"],
  "Caracaraí": ["Centro", "Novo Horizonte"],

  // ── RIO GRANDE DO SUL ─────────────────────────────────────────────────────
  "Porto Alegre": ["Centro", "Bela Vista", "Bom Fim", "Cidade Baixa", "Floresta", "Independência", "Jardim Botânico", "Menino Deus", "Moinhos de Vento", "Navegantes", "Petrópolis", "Passo d'Areia", "Santana", "São Geraldo", "Tristeza", "Vila Nova", "Cristal", "Cavalhada", "Auxiliadora", "Rio Branco", "Mont Serrat", "Santa Cecília", "Nonoai", "Teresópolis", "Partenon", "Medianeira", "Sarandi", "Passo das Pedras", "Jardim Itu", "Glória", "Ipanema", "Restinga", "Agronomia", "Lomba do Pinheiro", "Bom Jesus", "Higienópolis", "Rubem Berta", "Cristo Redentor", "Humaitá", "Chácara das Pedras", "Vila Jardim", "Boa Vista"],
  "Caxias do Sul": ["Centro", "Ana Rech", "Cruzeiro", "Lourdes", "Moinhos D'Água", "Santa Lúcia", "São Marcos", "Desvio Rizzo", "São Pelegrino"],
  "Pelotas": ["Centro", "Areal", "Fragata", "Laranjal", "Três Vendas", "Simões Lopes", "Dunas", "Navegantes"],
  "Canoas": ["Centro", "Estância Velha", "Igara", "Niterói", "Mathias Velho", "Marechal Rondon"],
  "Santa Maria": ["Centro", "Bonfim", "Camobi", "Dores", "Nossa Senhora de Fátima", "Urlândia", "Pinheiro Machado"],
  "Novo Hamburgo": ["Centro", "Canudos", "Operário", "Rincão", "Primavera", "Rio dos Sinos"],
  "Passo Fundo": ["Centro", "Boqueirão", "Lucas de Oliveira", "Vera Cruz", "Petrópolis", "São Cristóvão"],
  "São Leopoldo": ["Centro", "Colonial", "Rio dos Sinos", "Santos Dumont", "Vicentina"],
  "Gravataí": ["Centro", "Morada do Vale", "Santa Fé"],
  "Viamão": ["Centro", "Viamópolis", "Itapuã"],
  "Alvorada": ["Centro", "Jardim Mauá", "Bom Sucesso"],
  "Rio Grande": ["Centro", "Cidade Nova", "Cassino", "Junção"],
  "Bagé": ["Centro", "Colégio", "Nilo Brites"],
  "Bento Gonçalves": ["Centro", "Fátima", "São Roque"],
  "Uruguaiana": ["Centro", "Medianeira", "Franco Madero"],

  // ── SANTA CATARINA ────────────────────────────────────────────────────────
  "Florianópolis": ["Centro", "Agronômica", "Coqueiros", "Córrego Grande", "Ingleses", "Itacorubi", "Lagoa da Conceição", "Pantanal", "Saco dos Limões", "Santa Mônica", "Trindade", "Canasvieiras", "Jurerê", "Cacupé", "Santo Antônio de Lisboa", "Rio Tavares", "Campeche", "Armação", "Pântano do Sul"],
  "Joinville": ["Centro", "Anita Garibaldi", "Boa Vista", "Bucarein", "Floresta", "Glória", "Itaum", "Petrópolis", "Saguaçu", "América", "Costa e Silva", "Fátima", "Iririú", "Jardim Iririú"],
  "Blumenau": ["Centro", "Itoupava Norte", "Passo Manso", "Victor Konder", "Velha", "Garcia", "Ponta Aguda", "Itoupava Central", "Água Verde"],
  "São José": ["Centro", "Campinas", "Floresta", "Kobrasol", "Ipiranga", "Barreiros"],
  "Chapecó": ["Centro", "Efapi", "Passo dos Fortes", "São Cristóvão", "Palmital", "Jardim Itália"],
  "Itajaí": ["Centro", "Cidade Nova", "Cordeiros", "São João", "Espinheiros", "Fazenda"],
  "Criciúma": ["Centro", "Comerciário", "Jardim Angélica", "Santa Bárbara", "Próspera", "Michel"],
  "Lages": ["Centro", "Coral", "Petrópolis", "São Luís", "Centenário"],
  "Palhoça": ["Centro", "Pagani", "Passa Vinte"],
  "Balneário Camboriú": ["Centro", "Barra", "Nações", "Das Nações"],
  "Brusque": ["Centro", "Santa Luzia", "Don Afonso"],
  "Tubarão": ["Centro", "Dehon", "Humaitá"],
  "Jaraguá do Sul": ["Centro", "Água Verde", "Estrada Nova"],
  "Concórdia": ["Centro", "São Pedro", "Santa Cruz"],

  // ── SERGIPE ───────────────────────────────────────────────────────────────
  "Aracaju": ["Centro", "13 de Julho", "Atalaia", "Grageru", "Inácio Barbosa", "Jardins", "Luzia", "Pereira Lobo", "São José", "Siqueira Campos", "Suíssa", "Farolândia", "Augusto Franco", "Santos Dumont", "Cirurgia", "São Conrado"],
  "Nossa Senhora do Socorro": ["Centro", "João Alves", "Marcos Freire I", "Marcos Freire II", "Cohab"],
  "Lagarto": ["Centro", "Alto do Céu", "Novo Horizonte", "Cohab"],
  "Itabaiana": ["Centro", "Betânia", "Boa Vista", "Jardim Campo Novo"],
  "São Cristóvão": ["Centro", "Rosa Elze", "Jardim Universitário"],
  "Simão Dias": ["Centro", "Novo Horizonte"],
  "Propriá": ["Centro", "São Francisco"],

  // ── SÃO PAULO ─────────────────────────────────────────────────────────────
  "São Paulo": ["Centro", "Consolação", "Pinheiros", "Vila Madalena", "Itaim Bibi", "Moema", "Vila Mariana", "Tatuapé", "Santana", "Perdizes", "Bela Vista", "Liberdade", "Brás", "Mooca", "Ipiranga", "Penha", "Lapa", "Pirituba", "Santo Amaro", "Campo Belo", "Jabaquara", "Saúde", "Morumbi", "Brooklin", "Tremembé", "Cambuci", "Bom Retiro", "Cerqueira César", "Jardins", "Vila Prudente", "Sapopemba", "Cidade Tiradentes", "Jardim Ângela", "Capão Redondo", "Campo Limpo", "Vila Sônia", "Butantã", "Rio Pequeno", "Raposo Tavares", "Limão", "Tucuruvi", "Vila Guilherme", "Belém", "Água Rasa", "Vila Formosa", "Anália Franco", "Parque do Carmo", "Itaquera", "Guaianases", "Lajeado", "Ermelino Matarazzo", "Itaim Paulista", "Perus", "Jaraguá", "Brasilândia", "Vila Nova Cachoeirinha", "Casa Verde", "Mandaqui", "Horto Florestal", "Lauzane Paulista"],
  "Guarulhos": ["Centro", "Macedo", "Jardim São João", "Pimentas", "Bonsucesso", "Cumbica", "Ponte Grande", "Presidente Dutra", "Jardim Cumbica", "Vila Augusta", "Vila Galvão", "Parque Continental", "Taboão"],
  "Campinas": ["Centro", "Cambuí", "Taquaral", "Barão Geraldo", "Botafogo", "Guanabara", "Jardim Chapadão", "Nova Campinas", "Parque São Quirino", "Swift", "Vila Industrial", "Mansões Santo Antônio", "Sousas", "Joaquim Egídio", "Parque Itália", "Bosque", "Jardim Aurélia", "Jardim Santa Genebra", "Satélite Íris", "Tropical"],
  "São Bernardo do Campo": ["Centro", "Assunção", "Baeta Neves", "Ferrazópolis", "Jardim do Mar", "Nova Petrópolis", "Rudge Ramos", "Demarchi", "Paulicéia"],
  "Santo André": ["Centro", "Campestre", "Jardim Bela Vista", "Recreio da Borda do Campo", "Vila Bastos", "Paraíso", "Casa Branca", "Utinga"],
  "Osasco": ["Centro", "Bonfim", "City Bussocaba", "Jardim Roberto", "Km 18", "Umuarama", "Quitaúna", "Presidente Altino"],
  "Sorocaba": ["Centro", "Além Ponte", "Éden", "Jardim Paulistano", "Wanel Ville", "Jardim Ibiti", "Vitória Régia"],
  "Ribeirão Preto": ["Centro", "Alto da Boa Vista", "Jardim Paulista", "Nova Ribeirânia", "Sumarezinho", "Jardim Sumaré", "Jardim Botânico", "Ipiranga", "Vila Tibério"],
  "Mauá": ["Centro", "Jardim Zaíra", "Vila Assis Brasil", "Paranavaí", "Área Rural"],
  "São Caetano do Sul": ["Centro", "Barcelona", "Prosperidade", "Santa Paula", "Boa Vista"],
  "Mogi das Cruzes": ["Centro", "Vila Mogilar", "Jardim Camargo", "Brás Cubas", "Jundiapeba"],
  "Piracicaba": ["Centro", "Jardim Oriente", "Nova América", "Paulista", "Santa Teresinha", "Vila Rezende"],
  "Bauru": ["Centro", "Jardim Bela Vista", "Bela Vista", "Mary Dota", "Jardim Panorama", "Vila Universitária"],
  "Santos": ["Centro", "Gonzaga", "Boqueirão", "Ponta da Praia", "Aparecida", "Campo Grande", "Marapé"],
  "Jundiaí": ["Centro", "Vila Arens", "Jardim Paulista", "Medeiros", "Anhangabaú"],
  "Limeira": ["Centro", "Jardim Boa Esperança", "Jardim Piratininga", "Centro Cívico"],
  "Franca": ["Centro", "Jardim Aeroporto", "Jardim América", "Jardim Planalto"],
  "Taubaté": ["Centro", "Jardim das Nações", "Vila Aparecida", "Bom Conselho"],
  "Carapicuíba": ["Centro", "Cohab", "Jardim Santa Filomena"],
  "São José dos Campos": ["Centro", "Jardim Aquarius", "Campos de São José", "Jardim Esplanada", "Vista Verde"],
  "Diadema": ["Centro", "Piraporinha", "Eldorado", "Serraria"],
  "Suzano": ["Centro", "Jardim Imperador", "Vila Maluf"],
  "Taboão da Serra": ["Centro", "Jardim Monte Alegre", "Jardim Apurá"],
  "Barueri": ["Centro", "Alphaville", "Jardim Silveira", "Jardim Bonança"],
  "Americana": ["Centro", "Jardim Brasil", "Jardim São Paulo", "Praia Azul"],
  "São Carlos": ["Centro", "Cidade Aracy", "Jardim Jockey Club", "Santa Felícia"],
  "Araraquara": ["Centro", "Jardim Novo Araraquara", "Jardim Marchetti", "Vila Xavier"],
  "Presidente Prudente": ["Centro", "Jardim Bongiovani", "Jardim Paulista", "Parque do Povo"],
  "Marília": ["Centro", "Jardim América", "Jardim Cavalari", "Nova Marília"],
  "Rio Claro": ["Centro", "Jardim Floridiana", "Novo Jardim Wenzel"],
  "Araçatuba": ["Centro", "Caraguatá", "Jardim Nova Yorque"],
  "São José do Rio Preto": ["Centro", "Boa Vista", "Jardim Paulista", "Pinheiros"],
  "Jacareí": ["Centro", "Jardim das Indústrias", "Vila Machado"],
  "Indaiatuba": ["Centro", "Jardim Morada do Sol"],
  "Hortolândia": ["Centro", "Jardim Novo Ângulo", "Parque Via Norte"],
  "Praia Grande": ["Centro", "Ocian", "Caiçara", "Aviação"],
  "São Vicente": ["Centro", "Catarina", "Parque Bitaru", "Vila Valença"],
  "Botucatu": ["Centro", "Jardim Paraíso", "Jardim Brasil", "Rubião Júnior"],
  "Itu": ["Centro", "Vila Aparecida", "Jardim Europa"],
  "Sumaré": ["Centro", "Jardim Nova Veneza", "Nova Veneza"],
  "Guarujá": ["Centro", "Enseada", "Astúrias", "Pitangueiras"],

  // ── TOCANTINS ─────────────────────────────────────────────────────────────
  "Palmas": ["Centro", "Plano Diretor Norte", "Plano Diretor Sul", "Aureny I", "Aureny II", "Jardim Aureny III", "Santa Bárbara", "Taquaralto", "Lago Norte", "Jardim Taquari"],
  "Araguaína": ["Centro", "Setor Araguaína Sul", "Colégio", "Setor Central", "Setor Maracanã", "Setor Industrial"],
  "Gurupi": ["Centro", "Setor Sul", "Setor Norte", "Jardim Bela Vista"],
  "Porto Nacional": ["Centro", "Jardim dos Ipês", "Loteamento Jardins", "Setor Aeroporto"],
  "Paraíso do Tocantins": ["Centro", "Setor Universitário", "Jardim das Palmeiras"],
  "Colinas do Tocantins": ["Centro", "Novo Horizonte", "Setor Sul"],
};

export function getCidades(estado: string): string[] {
  return [...new Set(cidades[estado] || [])].sort();
}

export function getBairros(cidade: string): string[] {
  return [...new Set(bairros[cidade] || [])].sort();
}
